spring.application.name=library-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/altis_library
spring.datasource.username=postgres
spring.datasource.password=root

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.properties.hibernate.jdbc.lab.non_contextual_creation=true

spring.security.user.name=user
spring.security.user.password=root
